baseURL = "https://blog.jcatania.io/"
languageCode = "fr-fr"
title = "Blog JCatania.io"
copyright = "Â© Julien Catania {year}"
theme = "codex"
enableEmoji = true
googleAnalytics="UA-34338750-4"
[params]
  github = "https://github.com/j-catania"

# Controls the navigation
[[menu.main]]
identifier = "about"
name = "about"
title = "About"
url = "/"

[[menu.main]]
identifier = "blog"
name = "blog"
title = "Blog"
url = "/blog"

# allows HTML in markdown files
[markup.goldmark.renderer]
unsafe= true
